#!/usr/bin/bash
cd ~/bot_ws
source install/setup.bash
ros2 launch slam_toolbox online_async_launch.py slam_params_file:=/home/phuoc/bot_ws/src/my_bot/config/mapper_params_online_async.yaml use_sim_time:=false
